import type { Node, NodeTypes } from "reactflow";
import { InputNode, InputNodeProps } from "./InputNode";

const fullModels: Omit<InputNodeProps, 'register'>[] = [
  {
    title: 'Trend / User Data Agent',
    description: "process initial data to the caption generator",
    placeholder: 'TBD',
    hasTextArea: true
  },
  {
    title: 'Level Caption Generator',
    description: "produce the level captions based on data",
    placeholder: 'TBD',
    hasTextArea: true

  },
  {
    title: 'Caption to Image Prompt',
    description: "transform caption into fully detailed image prompt",
    placeholder: `Pic Wiz is your ultimate destination for picture-guessing fun with friends. Imagine merging the thrill of art-based riddles with the joy of multiplayer collaboration. Enter Pic Wiz – the perfect game for sharpening your mind while connecting with others.
    In Pic Wiz, it's not just about what you see but how you think and solve with your friends. How effectively can you and your team analyze images to uncover hidden objects or phrases? Can you work together to decipher the artistic clues? Engage in this exciting challenge, where teamwork and strategy combine to create a unique, brain-teasing experience. Get ready for endless fun as you.
    Here are examples of caption and level description output:
    
    caption: I have a dream
    level output: Martin Luther King, sleeping on a cloud. Realistic 3d render Pixar style. 32k. pastel colors, with a light solid background
    
    caption: better late than never
    level output: Realistic 3d render of An 70-year-old woman smiles in her graduation clothes, and lots of young students in their graduation clothes. Everyone is wearing the same clothes. Pixar style. 32k. pastel colors, with a light solid background
    
    caption: ceaser salad
    level output: Realistic 3d render of A Roman emperor cutting a salad. Pixar style. 32k. pastel colors, with a light solid background
    
    capition: do not judge a book by its cover
    level output: Realistic 3d render of A judge in court holds a book. with a white wig. Pixar style. 32k. pastel colors, with a light solid background
    
    caption: mac and cheese
    level output: A Mac computer with a slice of cheese on the side
    
    caption: turtleneck
    level output: A tattoo of a turtle on the neck
    
    The best captions are descriptions of images that can embody the caption.
    Please stick to the facts - try to create accurate representation.
    from now on I will query with a caption and you should only responsd with a level output
    `,
    hasTextArea: true

  },
  {
    title: 'Image Generator',
    description: `produce level caption image.
    using gen AI to model a complementary level based on the
    image-specific prompt engineering
    generated by the previous gen AI model`,
    placeholder: '',
    hasTextArea: false

  },
  {
    title: 'Image Processing',
    description: `Refocus and Resize image.
    Move the level image to the top and create a place
    for the AI to add a solid background for the level screen`,
    placeholder: '',
    hasTextArea: false
  },
  {
    title: 'Background Generator',
    description: "created background for the image",
    placeholder: 'add solid background',
    hasTextArea: true
  },
]


export const getInitialNodes = (register: any) => [
  ...fullModels.map((data, i) => ({
    id: i.toString(),
    type: 'InputNode',
    data: {
      ...data,
      register,
      input: '',
    },
    position: {
      x: i * 350,
      y: i * (-40),
    }
  }))
] satisfies Node[];



export const nodeTypes = {
  "InputNode": InputNode
  // Add any of your custom nodes here!
} satisfies NodeTypes;
